# Generated by Django 4.1.3 on 2024-01-19 11:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_teachers'),
    ]

    operations = [
        migrations.AddField(
            model_name='teachers',
            name='lastname',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
    ]
