# Generated by Django 4.1.3 on 2024-01-19 11:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0003_teachers_lastname'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='middlename',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
    ]
