# Generated by Django 4.1.3 on 2024-01-19 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0004_students_middlename'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='housename',
            field=models.CharField(default='unknown', max_length=255),
        ),
    ]
