# Generated by Django 4.1.3 on 2024-01-20 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0005_students_housename'),
    ]

    operations = [
        migrations.AddField(
            model_name='teachers',
            name='middlename',
            field=models.CharField(default='unknown', max_length=255),
        ),
    ]
