# Generated by Django 4.1.3 on 2024-01-20 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0006_teachers_middlename'),
    ]

    operations = [
        migrations.AddField(
            model_name='teachers',
            name='mobile',
            field=models.IntegerField(default= 1),
        ),
    ]
