# Generated by Django 4.1.3 on 2024-01-20 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0007_teachers_mobile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teachers',
            name='mobile',
            field=models.IntegerField(default=1),
        ),
    ]
