# Generated by Django 4.1.3 on 2024-01-20 06:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0012_alter_teachers_mobile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teachers',
            name='mobile',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
