# Generated by Django 4.1.3 on 2024-01-20 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0016_alter_teachers_mobile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teachers',
            name='mobile',
        ),
    ]
