# Generated by Django 4.1.3 on 2024-01-20 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0017_remove_teachers_mobile'),
    ]

    operations = [
        migrations.AddField(
            model_name='teachers',
            name='mobile',
            field=models.CharField(blank=True, default=1, max_length=15, null=True),
        ),
    ]
