# Generated by Django 4.1.3 on 2024-01-20 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0018_teachers_mobile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teachers',
            name='mobile',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
