# Generated by Django 4.1.3 on 2024-01-20 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0020_alter_teachers_mobile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teachers',
            old_name='mobile',
            new_name='mobile_no',
        ),
    ]
