# Generated by Django 4.1.3 on 2024-01-20 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0021_rename_mobile_teachers_mobile_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teachers',
            name='mobile_no',
        ),
        migrations.AddField(
            model_name='teachers',
            name='Phone_num',
            field=models.CharField(blank=True, default=1, max_length=15, null=True),
        ),
    ]
