# Generated by Django 4.1.3 on 2024-01-20 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0022_remove_teachers_mobile_no_teachers_phone_num'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teachers',
            name='Phone_num',
        ),
        migrations.AddField(
            model_name='students',
            name='Phone_num',
            field=models.CharField(blank=True, default=1, max_length=15, null=True),
        ),
    ]
