# Generated by Django 4.1.3 on 2024-01-20 07:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0024_alter_students_phone_num'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='students',
            name='Phone_num',
        ),
        migrations.AddField(
            model_name='students',
            name='mobile',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
