# Generated by Django 4.1.3 on 2024-01-20 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0025_remove_students_phone_num_students_mobile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='mobile',
            field=models.IntegerField(null=True),
        ),
    ]
