# Generated by Django 4.1.3 on 2024-01-20 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0026_alter_students_mobile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='students',
            old_name='mobile',
            new_name='Phone',
        ),
    ]
