# Generated by Django 4.1.3 on 2024-01-20 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0027_rename_mobile_students_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='students',
            name='Phone',
        ),
        migrations.AddField(
            model_name='students',
            name='mobile',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
