# Generated by Django 4.1.3 on 2024-01-20 07:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0028_remove_students_phone_students_mobile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='mobile',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
