# Generated by Django 4.1.3 on 2024-01-20 07:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0029_alter_students_mobile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='students',
            name='mobile',
        ),
        migrations.AddField(
            model_name='students',
            name='fathername',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
