# Generated by Django 4.1.3 on 2024-01-20 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0030_remove_students_mobile_students_fathername'),
    ]

    operations = [
        migrations.AddField(
            model_name='teachers',
            name='mobile',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
