# Generated by Django 4.1.3 on 2024-01-20 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0031_teachers_mobile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teachers',
            name='mobile',
            field=models.IntegerField(default=1, max_length=10),
        ),
    ]
