# Generated by Django 4.1.3 on 2024-01-20 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0032_alter_teachers_mobile'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='mobile',
            field=models.IntegerField(default=1, max_length=10),
        ),
    ]
