# Generated by Django 4.1.3 on 2024-01-25 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0033_students_mobile'),
    ]

    operations = [
        migrations.CreateModel(
            name='departments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('depname', models.CharField(max_length=255)),
                ('depcode', models.CharField(max_length=255)),
            ],
        ),
    ]
