# Generated by Django 4.2.16 on 2024-11-17 10:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0034_departments'),
    ]

    operations = [
        migrations.AddField(
            model_name='teachers',
            name='dep',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
    ]
