# Generated by Django 4.2.16 on 2024-11-17 11:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0035_teachers_dep'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='depart',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='teachers',
            name='middlename',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='teachers',
            name='mobile',
            field=models.IntegerField(max_length=10),
        ),
    ]
