# Generated by Django 4.2.16 on 2024-11-18 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0036_students_depart_alter_teachers_middlename_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teachers',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='teacher_photos/'),
        ),
        migrations.AlterField(
            model_name='students',
            name='housename',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='students',
            name='mobile',
            field=models.IntegerField(max_length=10),
        ),
    ]
