# Generated by Django 4.2.16 on 2024-11-18 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0037_teachers_image_alter_students_housename_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teachers',
            old_name='image',
            new_name='photo',
        ),
        migrations.AlterField(
            model_name='students',
            name='mobile',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='teachers',
            name='mobile',
            field=models.IntegerField(),
        ),
    ]
