# Generated by Django 4.2.16 on 2024-11-19 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0038_rename_image_teachers_photo_alter_students_mobile_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teachers',
            name='emailid',
            field=models.EmailField(default='none', max_length=254),
        ),
    ]
