# Generated by Django 4.2.16 on 2024-11-19 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0039_teachers_emailid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teachers',
            name='emailid',
            field=models.EmailField(max_length=254),
        ),
    ]
