# Generated by Django 4.2.16 on 2024-11-19 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0040_alter_teachers_emailid'),
    ]

    operations = [
        migrations.AddField(
            model_name='teachers',
            name='designation',
            field=models.CharField(default='none', max_length=255),
        ),
    ]
