# Generated by Django 4.2.16 on 2024-11-19 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0041_teachers_designation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teachers',
            name='designation',
            field=models.CharField(max_length=255),
        ),
    ]
